language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
before_install:
  - pip install --upgrade pip
  - pip install pep8 pylint
install:
  - python setup.py sdist
  - pip install ./dist/*
script:
  - pep8 backlog setup.py
  - pylint backlog setup.py
  - python -m unittest discover
