language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
branches:
  only:
    - master
before_install:
  - pip install --upgrade pip
  - pip install pep8 pylint tox
install:
  - python setup.py sdist
  - pip install ./dist/*
script:
  - tox
  - pep8 backlog setup.py
  - pylint backlog setup.py
