name: Documentation
on:
  release:
    types: [created]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - run: git checkout gh-pages
    - run: python -m pip install --upgrade tox
    - run: tox -- "$GITHUB_REF"
    - run: .tox/gh-pages/bin/verdoc-index "$GITHUB_REF/"
    - run: git add -A
    - run: git commit -m "Add docs for $GITHUB_REF"
    - run: git config credential.helper '!f() { echo "username=${GIT_USERNAME}"; echo "password=${GIT_PASSWORD}"; }; f'
    - env:
        GIT_USERNAME: ${{ secrets.GITHUB_USERNAME }}
        GIT_PASSWORD: ${{ secrets.GITHUB_PASSWORD }}
      run: git push
